# Generated by Django 3.0.5 on 2020-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccountCreationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='AccountNumber',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='Balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
