# Generated by Django 3.0.5 on 2020-04-29 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transaction_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Sender', models.CharField(max_length=255)),
                ('Receiver', models.CharField(max_length=255)),
                ('Sender_acc', models.IntegerField()),
                ('Receiver_acc', models.IntegerField()),
                ('Transaction_Value', models.IntegerField()),
                ('Sender_Balance', models.IntegerField()),
                ('Receiver_Balance', models.IntegerField()),
            ],
        ),
    ]
